name: .NET Build & Publish (Local Runner)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify .NET installed
        run: dotnet --version

      - name: Restore
        run: dotnet restore
          
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Debug repo structure
        shell: powershell
        run: |
          Write-Host "Current path:"
          pwd
          Write-Host "Listing repo root:"
          dir
    
      - name: Build & publish .NET app locally
        shell: powershell
        run: |
          $publishPath = "C:\deployments\runner-poc"
          New-Item -ItemType Directory -Force -Path $publishPath
          dotnet publish RunnerPOC.csproj -c Release -o $publishPath

